### ISSUE TITLE
Set up FS project

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-trash-it#1]
## Value proposition

As a developer
I want to set up a fullstack project
<So that...>

## Acceptance criteria

- [ ] FS-project has a Spring Boot module with MongoDB integration
- [ ] FS-project has a React typescript module

## Tasks
- [ ] Set up FS-project
