### ISSUE TITLE
Set up CI on GitHub

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-trash-it#2]
## Value proposition

As a developer
I want to integrate a CI on GitHub for the repo 
So that it auomatically trggered on ever push for the main branch

## Acceptance criteria

- [ ] FS-project has a workflows directory
- [ ] FS-project has a YAML file with adjusted code

## Tasks

- [ ] Create a directory .github/workflows in repository
- [ ] Create a YAML file in this directory
