### ISSUE TITLE
SetUp: Implement CD with Docker

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-trash-it#4]
## Value proposition

As a developer
I want to use CD with Docker
So that I can be certain the application works the same in any environment

## Acceptance criteria

- [ ] FS-project has a dockerfile
- [ ] pom has a fileName-tag
- [ ] An image from dockerfile was build

## Tasks

- [ ] Run build-process for frontend
- [ ] Adjust static folder in backend
- [ ] Create new dockerfile  
- [ ] Implement the following, adapted code to the dockerfile

```
FROM --platform=linux/amd64 openjdk:20
LABEL maintainer="john.doe@neuefische.de"
EXPOSE 8080
ADD backend/target/app.jar app.jar
CMD [ "sh", "-c", "java -jar /app.jar" ]
```
- [ ] Change the app's name to trash-it in the pom.xml-file
- [ ] Adjust new naming for JARfile in the dockerfile
- [ ] Build backend with maven (lifecycle --> package)
- [ ] Build app with docker
