### ISSUE TITLE
SetUp: Implement branch protection

### ISSUE THREAD

**Issue by tejue** [tejue/capstone-trash-it#5]
## Value proposition

As a developer
I want the main branch to be protected
So that the production code remains clean

## Acceptance criteria

- [ ] No pushes on main branch are possible
- [ ] Merge is only possible after 1 review of a collaborateur 

## Tasks

- [ ] Clean frontend Code
- [ ] Protect branch on GitHub-Settings
- [ ] Invite collaborateurs for PRs
